### ISSUE TITLE
Still receiving error related to rawToChar

### ISSUE THREAD

**Issue by natearoe** [DheerajAgarwal/rgdax#20]
I have downloaded the latest version of rgdax. 

library(devtools)
install_github("DheerajAgarwal/rgdax", ref="dev")

But I am still receive this error that has been discussed in the past in response to the accounts() function:

 Error in rawToChar(getURLContent(url = url, curl = getCurlHandle(useragent = "R"),  : 
  argument 'x' must be a raw vector 

My understanding is that the fix for this has been incorporated into the latest version on GitHub, so this should not happen any longer.

Any suggestions? 

Thanks!

**Comment by DheerajAgarwal** [comment]
This issue was occurring earlier and was subsequently closed. Can you confirm a few things for me please.
1. Which OS are you using?
2. Which R version?
2. Are there other functions (apart from `accounts`) where you have noticed or can replicate the issue?

**Comment by DheerajAgarwal** [comment]
Looking it a bit more closely, the issue should not occur because the functions for `rawToChar` were removed. Can you please try again after uninstalling the version from CRAN and github and then reinstalling the `dev` branch version of the code from github. I have just tried the functions on both windows and mac and unable to reprodcuce the issue with the latest dev code.

**Comment by natearoe** [comment]
Thank you Dheeraj Agarwal, 

I had originally installed rgdax from GitHub. I encountered the issue with rawToChar. I found the documentation here on GitHub. I uninstalled the package and downloaded the dev version from GitHub. I continued to encounter the rawToChar error, though. After restarting my computer, the rawToChar error stopped. 

Hope this helps for anyone that might experience something similar and thank you for the prompt response.
