### ISSUE TITLE
Thanks and question about the future

### ISSUE THREAD

**Issue by angelaponte** [DheerajAgarwal/rgdax#6]
Thank you for putting the time into building this package and sharing it with us. The public_candles function has been especially useful to me these last 6 months.

Do we expect that the CRAN package will no longer work as of January 1, 2019, due to Coinbase deprecation of the GDAX API endpoints?

If so, is it a simple URL change in the code to the new Coinbase Pro API endpoint or is the fix more involved?

Thanks again!

**Comment by DheerajAgarwal** [comment]
@angelaponte that will indeed be the case in a couple of days. the CRAN version is deprecated and will stop working. 

I am in the process of releasing the new version on CRAN, however my testing has run into some issues (i lost my authenticator codes due to a change in phone).  I am working with Coinbase to restore my accounts. This could take some time but rest assured that the work is in progress.

In the meanwhile, the `dev` branch is now up to date with all necessary changes. You should be able to install it directly from github using the instructions in the `README.md` file. Since I haven't been able to test it completely, i will encourage some user testing and feedback too.

**Comment by angelaponte** [comment]
Thanks for the tip; I updated the package using the dev branch and the two functions I've been using, public_candles() and public_time() are both working. That was a smooth transition for me.

I'll be calling both functions automatically and manually for the foreseeable future.
